# Generated by Django 3.1.2 on 2020-10-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
